# Generated by Django 3.2 on 2021-05-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
