# Generated by Django 3.2 on 2021-05-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='modifiedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
